module.exports = {
  apps: [
    {
      name: 'kerimbilgisayar',
      script: 'dist/server.cjs',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1536M',
      min_uptime: '30s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      max_restarts: 1000,
      kill_timeout: 8000,
      listen_timeout: 10000,
      time: true,
      env: {
        NODE_ENV: 'production',
        DATABASE_HOST: process.env.DATABASE_HOST,
        DATABASE_NAME: process.env.DATABASE_NAME,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
        DATABASE_PORT: process.env.DATABASE_PORT,
        DATABASE_USER: process.env.DATABASE_USER,
        DATABASE_URL: process.env.DATABASE_URL,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        APP_URL: process.env.APP_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
      },
    },
  ],
};
