import express from 'express';
import { publicRouter } from './public.routes';
import { customerRouter } from './customer.routes';
import { authRouter } from './auth.routes';
import { servicesRouter } from './services.routes';
import { translationsRouter } from './translations.routes';
import { ticketsRouter } from './tickets.routes';
import { dealersRouter } from './dealers.routes';
import { financeRouter } from './finance.routes';
import { notificationsRouter } from './notifications.routes';
import { logisticsRouter } from './logistics.routes';
import { dashboardRouter } from './dashboard.routes';
import { stockRouter } from './stock.routes';
import { salesRouter } from './sales.routes';
import { settingsRouter } from './settings.routes';
import { usersRouter } from './users.routes';
import { customersRouter } from './customers.routes';
import { contentRouter } from './content.routes';
import { mediaRouter } from './media.routes';
import { integrationsRouter } from './integrations.routes';
import { webhooksRouter } from './webhooks.routes';
import { invoicesRouter } from './invoices.routes';
import { reportsRouter } from './reports.routes';

export const routes = express.Router();

routes.use(publicRouter);
routes.use(customerRouter);
routes.use(authRouter);
routes.use(servicesRouter);
routes.use(translationsRouter);
routes.use(ticketsRouter);
routes.use(dealersRouter);
routes.use(financeRouter);
routes.use(notificationsRouter);
routes.use(logisticsRouter);
routes.use(dashboardRouter);
routes.use(stockRouter);
routes.use(salesRouter);
routes.use(settingsRouter);
routes.use(usersRouter);
routes.use(customersRouter);
routes.use(contentRouter);
routes.use(mediaRouter);
routes.use(integrationsRouter);
routes.use(webhooksRouter);
routes.use(invoicesRouter);
routes.use(reportsRouter);
